sbatch server_script_therm.sh bell_state_reach bell_state_reach_0_therm "bellman convex" yorktown 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_1_therm "bellman convex" athens 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_2_therm "bellman convex" vigo 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_3_therm "bellman convex" belem 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_4_therm "bellman convex" valencia 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_5_therm "bellman convex" bogota 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_6_therm "bellman convex" santiago 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_7_therm "bellman convex" rome 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_8_therm "bellman convex" burlington 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_9_therm "bellman convex" quito 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_10_therm "bellman convex" ourense 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_11_therm "bellman convex" essex 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_12_therm "bellman convex" manila 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_13_therm "bellman convex" london 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_14_therm "bellman convex" lima 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_15_therm "bellman convex" lagos 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_16_therm "bellman convex" perth 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_17_therm "bellman convex" casablanca 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_18_therm "bellman convex" oslo 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_19_therm "bellman convex" nairobi 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_20_therm "bellman convex" jakarta 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_21_therm "bellman convex" perfect_hardware 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_22_therm "bellman convex" melbourne 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_23_therm "bellman convex" guadalupe 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_24_therm "bellman convex" almaden 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_25_therm "bellman convex" boeblingen 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_26_therm "bellman convex" singapore 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_27_therm "bellman convex" johannesburg 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_28_therm "bellman convex" poughkeepsie 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_29_therm "bellman convex" kolkata 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_30_therm "bellman convex" hanoi 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_31_therm "bellman convex" auckland 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_32_therm "bellman convex" montreal 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_33_therm "bellman convex" mumbai 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_34_therm "bellman convex" geneva 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_35_therm "bellman convex" toronto 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_36_therm "bellman convex" sydney 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_37_therm "bellman convex" cairo 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_38_therm "bellman convex" paris 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_39_therm "bellman convex" algiers 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_40_therm "bellman convex" cambridge 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_41_therm "bellman convex" rochester 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_42_therm "bellman convex" brooklyn 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_43_therm "bellman convex" manhattan 1 3
sbatch server_script_therm.sh bell_state_reach bell_state_reach_44_therm "bellman convex" washington 1 3
