sbatch server_script.sh bell_state_reach bell_state_reach_0 "bellman convex" yorktown,jakarta,cambridge 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_1 "bellman convex" athens,perfect_hardware 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_2 "bellman convex" vigo,melbourne,rochester 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_3 "bellman convex" belem,guadalupe,brooklyn 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_4 "bellman convex" valencia,almaden,manhattan 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_5 "bellman convex" bogota,boeblingen 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_6 "bellman convex" santiago,singapore 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_7 "bellman convex" rome,johannesburg 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_8 "bellman convex" burlington,poughkeepsie 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_9 "bellman convex" quito,kolkata 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_10 "bellman convex" ourense,hanoi,washington 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_11 "bellman convex" essex,auckland 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_12 "bellman convex" manila,montreal 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_13 "bellman convex" london,mumbai 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_14 "bellman convex" lima,geneva 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_15 "bellman convex" lagos,toronto 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_16 "bellman convex" perth,sydney 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_17 "bellman convex" casablanca,cairo 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_18 "bellman convex" oslo,paris 1 4
sbatch server_script.sh bell_state_reach bell_state_reach_19 "bellman convex" nairobi,algiers 1 4
