sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_0_therm bellman yorktown 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_1_therm bellman athens 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_2_therm bellman vigo 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_3_therm bellman belem 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_4_therm bellman valencia 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_5_therm bellman bogota 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_6_therm bellman santiago 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_7_therm bellman rome 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_8_therm bellman burlington 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_9_therm bellman quito 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_10_therm bellman ourense 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_11_therm bellman essex 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_12_therm bellman manila 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_13_therm bellman london 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_14_therm bellman lima 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_15_therm bellman lagos 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_16_therm bellman perth 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_17_therm bellman casablanca 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_18_therm bellman oslo 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_19_therm bellman nairobi 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_20_therm bellman jakarta 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_21_therm bellman perfect_hardware 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_22_therm bellman melbourne 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_23_therm bellman guadalupe 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_24_therm bellman almaden 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_25_therm bellman boeblingen 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_26_therm bellman singapore 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_27_therm bellman johannesburg 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_28_therm bellman poughkeepsie 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_29_therm bellman kolkata 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_30_therm bellman hanoi 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_31_therm bellman auckland 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_32_therm bellman montreal 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_33_therm bellman mumbai 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_34_therm bellman geneva 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_35_therm bellman toronto 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_36_therm bellman sydney 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_37_therm bellman cairo 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_38_therm bellman paris 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_39_therm bellman algiers 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_40_therm bellman cambridge 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_41_therm bellman rochester 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_42_therm bellman brooklyn 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_43_therm bellman manhattan 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_44_therm bellman washington 3 4
