sbatch server_script.sh bitflip_cxh bitflip_cxh_0 bellman yorktown,jakarta,cambridge 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_1 bellman athens,perfect_hardware 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_2 bellman vigo,melbourne,rochester 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_3 bellman belem,guadalupe,brooklyn 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_4 bellman valencia,almaden,manhattan 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_5 bellman bogota,boeblingen 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_6 bellman santiago,singapore 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_7 bellman rome,johannesburg 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_8 bellman burlington,poughkeepsie 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_9 bellman quito,kolkata 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_10 bellman ourense,hanoi,washington 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_11 bellman essex,auckland 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_12 bellman manila,montreal 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_13 bellman london,mumbai 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_14 bellman lima,geneva 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_15 bellman lagos,toronto 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_16 bellman perth,sydney 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_17 bellman casablanca,cairo 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_18 bellman oslo,paris 7 7
sbatch server_script.sh bitflip_cxh bitflip_cxh_19 bellman nairobi,algiers 7 7
