sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_0 bellman yorktown,hanoi 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_1 bellman athens,auckland 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_2 bellman vigo,montreal 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_3 bellman belem,mumbai 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_4 bellman valencia,geneva 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_5 bellman bogota,toronto 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_6 bellman santiago,sydney 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_7 bellman rome,cairo 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_8 bellman burlington,paris 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_9 bellman quito,algiers 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_10 bellman ourense,cambridge 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_11 bellman essex 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_12 bellman manila,rochester 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_13 bellman london,brooklyn 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_14 bellman lima,manhattan 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_15 bellman lagos 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_16 bellman perth 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_17 bellman casablanca 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_18 bellman oslo 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_19 bellman nairobi 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_20 bellman jakarta,washington 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_21 bellman perfect_hardware 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_22 bellman melbourne 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_23 bellman guadalupe 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_24 bellman almaden 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_25 bellman boeblingen 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_26 bellman singapore 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_27 bellman johannesburg 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_28 bellman poughkeepsie 3 8
sbatch server_script.sh bitflip_ipma2 bitflip_ipma2_29 bellman kolkata 3 8
