sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_0_therm bellman yorktown 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_1_therm bellman athens 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_2_therm bellman vigo 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_3_therm bellman belem 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_4_therm bellman valencia 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_5_therm bellman bogota 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_6_therm bellman santiago 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_7_therm bellman rome 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_8_therm bellman burlington 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_9_therm bellman quito 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_10_therm bellman ourense 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_11_therm bellman essex 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_12_therm bellman manila 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_13_therm bellman london 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_14_therm bellman lima 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_15_therm bellman lagos 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_16_therm bellman perth 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_17_therm bellman casablanca 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_18_therm bellman oslo 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_19_therm bellman nairobi 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_20_therm bellman jakarta 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_21_therm bellman perfect_hardware 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_22_therm bellman melbourne 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_23_therm bellman guadalupe 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_24_therm bellman almaden 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_25_therm bellman boeblingen 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_26_therm bellman singapore 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_27_therm bellman johannesburg 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_28_therm bellman poughkeepsie 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_29_therm bellman kolkata 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_30_therm bellman hanoi 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_31_therm bellman auckland 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_32_therm bellman montreal 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_33_therm bellman mumbai 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_34_therm bellman geneva 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_35_therm bellman toronto 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_36_therm bellman sydney 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_37_therm bellman cairo 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_38_therm bellman paris 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_39_therm bellman algiers 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_40_therm bellman cambridge 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_41_therm bellman rochester 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_42_therm bellman brooklyn 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_43_therm bellman manhattan 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_44_therm bellman washington 7 7
