sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_0_therm bellman yorktown,jakarta,cambridge 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_1_therm bellman athens,perfect_hardware 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_2_therm bellman vigo,melbourne,rochester 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_3_therm bellman belem,guadalupe,brooklyn 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_4_therm bellman valencia,almaden,manhattan 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_5_therm bellman bogota,boeblingen 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_6_therm bellman santiago,singapore 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_7_therm bellman rome,johannesburg 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_8_therm bellman burlington,poughkeepsie 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_9_therm bellman quito,kolkata 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_10_therm bellman ourense,hanoi,washington 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_11_therm bellman essex,auckland 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_12_therm bellman manila,montreal 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_13_therm bellman london,mumbai 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_14_therm bellman lima,geneva 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_15_therm bellman lagos,toronto 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_16_therm bellman perth,sydney 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_17_therm bellman casablanca,cairo 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_18_therm bellman oslo,paris 3 7
sbatch server_script_therm.sh bitflip_ipma bitflip_ipma_19_therm bellman nairobi,algiers 3 7
