sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_0_therm bellman yorktown,jakarta,cambridge 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_1_therm bellman athens,perfect_hardware 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_2_therm bellman vigo,melbourne,rochester 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_3_therm bellman belem,guadalupe,brooklyn 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_4_therm bellman valencia,almaden,manhattan 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_5_therm bellman bogota,boeblingen 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_6_therm bellman santiago,singapore 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_7_therm bellman rome,johannesburg 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_8_therm bellman burlington,poughkeepsie 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_9_therm bellman quito,kolkata 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_10_therm bellman ourense,hanoi,washington 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_11_therm bellman essex,auckland 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_12_therm bellman manila,montreal 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_13_therm bellman london,mumbai 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_14_therm bellman lima,geneva 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_15_therm bellman lagos,toronto 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_16_therm bellman perth,sydney 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_17_therm bellman casablanca,cairo 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_18_therm bellman oslo,paris 7 7
sbatch server_script_therm.sh bitflip_cxh bitflip_cxh_19_therm bellman nairobi,algiers 7 7
