sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_0_therm bellman yorktown,jakarta,cambridge 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_1_therm bellman athens,perfect_hardware 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_2_therm bellman vigo,melbourne,rochester 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_3_therm bellman belem,guadalupe,brooklyn 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_4_therm bellman valencia,almaden,manhattan 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_5_therm bellman bogota,boeblingen 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_6_therm bellman santiago,singapore 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_7_therm bellman rome,johannesburg 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_8_therm bellman burlington,poughkeepsie 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_9_therm bellman quito,kolkata 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_10_therm bellman ourense,hanoi,washington 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_11_therm bellman essex,auckland 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_12_therm bellman manila,montreal 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_13_therm bellman london,mumbai 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_14_therm bellman lima,geneva 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_15_therm bellman lagos,toronto 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_16_therm bellman perth,sydney 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_17_therm bellman casablanca,cairo 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_18_therm bellman oslo,paris 3 4
sbatch server_script_therm.sh bitflip_ipma2 bitflip_ipma2_19_therm bellman nairobi,algiers 3 4
