sbatch server_script_therm.sh ghz3 ghz3_0_therm bellman yorktown 3 3
sbatch server_script_therm.sh ghz3 ghz3_1_therm bellman athens 3 3
sbatch server_script_therm.sh ghz3 ghz3_2_therm bellman vigo 3 3
sbatch server_script_therm.sh ghz3 ghz3_3_therm bellman belem 3 3
sbatch server_script_therm.sh ghz3 ghz3_4_therm bellman valencia 3 3
sbatch server_script_therm.sh ghz3 ghz3_5_therm bellman bogota 3 3
sbatch server_script_therm.sh ghz3 ghz3_6_therm bellman santiago 3 3
sbatch server_script_therm.sh ghz3 ghz3_7_therm bellman rome 3 3
sbatch server_script_therm.sh ghz3 ghz3_8_therm bellman burlington 3 3
sbatch server_script_therm.sh ghz3 ghz3_9_therm bellman quito 3 3
sbatch server_script_therm.sh ghz3 ghz3_10_therm bellman ourense 3 3
sbatch server_script_therm.sh ghz3 ghz3_11_therm bellman essex 3 3
sbatch server_script_therm.sh ghz3 ghz3_12_therm bellman manila 3 3
sbatch server_script_therm.sh ghz3 ghz3_13_therm bellman london 3 3
sbatch server_script_therm.sh ghz3 ghz3_14_therm bellman lima 3 3
sbatch server_script_therm.sh ghz3 ghz3_15_therm bellman lagos 3 3
sbatch server_script_therm.sh ghz3 ghz3_16_therm bellman perth 3 3
sbatch server_script_therm.sh ghz3 ghz3_17_therm bellman casablanca 3 3
sbatch server_script_therm.sh ghz3 ghz3_18_therm bellman oslo 3 3
sbatch server_script_therm.sh ghz3 ghz3_19_therm bellman nairobi 3 3
sbatch server_script_therm.sh ghz3 ghz3_20_therm bellman jakarta 3 3
sbatch server_script_therm.sh ghz3 ghz3_21_therm bellman perfect_hardware 3 3
sbatch server_script_therm.sh ghz3 ghz3_22_therm bellman melbourne 3 3
sbatch server_script_therm.sh ghz3 ghz3_23_therm bellman guadalupe 3 3
sbatch server_script_therm.sh ghz3 ghz3_24_therm bellman almaden 3 3
sbatch server_script_therm.sh ghz3 ghz3_25_therm bellman boeblingen 3 3
sbatch server_script_therm.sh ghz3 ghz3_26_therm bellman singapore 3 3
sbatch server_script_therm.sh ghz3 ghz3_27_therm bellman johannesburg 3 3
sbatch server_script_therm.sh ghz3 ghz3_28_therm bellman poughkeepsie 3 3
sbatch server_script_therm.sh ghz3 ghz3_29_therm bellman kolkata 3 3
sbatch server_script_therm.sh ghz3 ghz3_30_therm bellman hanoi 3 3
sbatch server_script_therm.sh ghz3 ghz3_31_therm bellman auckland 3 3
sbatch server_script_therm.sh ghz3 ghz3_32_therm bellman montreal 3 3
sbatch server_script_therm.sh ghz3 ghz3_33_therm bellman mumbai 3 3
sbatch server_script_therm.sh ghz3 ghz3_34_therm bellman geneva 3 3
sbatch server_script_therm.sh ghz3 ghz3_35_therm bellman toronto 3 3
sbatch server_script_therm.sh ghz3 ghz3_36_therm bellman sydney 3 3
sbatch server_script_therm.sh ghz3 ghz3_37_therm bellman cairo 3 3
sbatch server_script_therm.sh ghz3 ghz3_38_therm bellman paris 3 3
sbatch server_script_therm.sh ghz3 ghz3_39_therm bellman algiers 3 3
sbatch server_script_therm.sh ghz3 ghz3_40_therm bellman cambridge 3 3
sbatch server_script_therm.sh ghz3 ghz3_41_therm bellman rochester 3 3
sbatch server_script_therm.sh ghz3 ghz3_42_therm bellman brooklyn 3 3
sbatch server_script_therm.sh ghz3 ghz3_43_therm bellman manhattan 3 3
sbatch server_script_therm.sh ghz3 ghz3_44_therm bellman washington 3 3
