sbatch server_script.sh reset reset_0 "convex bellman" yorktown,jakarta,cambridge 2 8
sbatch server_script.sh reset reset_1 "convex bellman" athens,perfect_hardware,prague 2 8
sbatch server_script.sh reset reset_2 "convex bellman" vigo,melbourne,rochester 2 8
sbatch server_script.sh reset reset_3 "convex bellman" belem,guadalupe,brooklyn 2 8
sbatch server_script.sh reset reset_4 "convex bellman" valencia,almaden,manhattan 2 8
sbatch server_script.sh reset reset_5 "convex bellman" bogota,boeblingen,cusco 2 8
sbatch server_script.sh reset reset_6 "convex bellman" santiago,singapore,brisbane 2 8
sbatch server_script.sh reset reset_7 "convex bellman" rome,johannesburg,kawasaki 2 8
sbatch server_script.sh reset reset_8 "convex bellman" burlington,poughkeepsie,osaka 2 8
sbatch server_script.sh reset reset_9 "convex bellman" quito,kolkata,kyoto 2 8
sbatch server_script.sh reset reset_10 "convex bellman" ourense,hanoi,washington 2 8
sbatch server_script.sh reset reset_11 "convex bellman" essex,auckland,kyiv 2 8
sbatch server_script.sh reset reset_12 "convex bellman" manila,montreal,torino 2 8
sbatch server_script.sh reset reset_13 "convex bellman" london,mumbai,fez 2 8
sbatch server_script.sh reset reset_14 "convex bellman" lima,geneva,makarresh 2 8
sbatch server_script.sh reset reset_15 "convex bellman" lagos,toronto 2 8
sbatch server_script.sh reset reset_16 "convex bellman" perth,sydney 2 8
sbatch server_script.sh reset reset_17 "convex bellman" casablanca,cairo 2 8
sbatch server_script.sh reset reset_18 "convex bellman" oslo,paris 2 8
sbatch server_script.sh reset reset_19 "convex bellman" nairobi,algiers 2 8
