sbatch server_script_therm.sh reset reset_0_therm "convex bellman" yorktown,ourense,jakarta,hanoi,cambridge,washington 2 5
sbatch server_script_therm.sh reset reset_1_therm "convex bellman" athens,essex,perfect_hardware,auckland,prague,kyiv 2 5
sbatch server_script_therm.sh reset reset_2_therm "convex bellman" vigo,manila,melbourne,montreal,rochester,torino 2 5
sbatch server_script_therm.sh reset reset_3_therm "convex bellman" belem,london,guadalupe,mumbai,brooklyn,fez 2 5
sbatch server_script_therm.sh reset reset_4_therm "convex bellman" valencia,lima,almaden,geneva,manhattan,makarresh 2 5
sbatch server_script_therm.sh reset reset_5_therm "convex bellman" bogota,lagos,boeblingen,toronto,cusco 2 5
sbatch server_script_therm.sh reset reset_6_therm "convex bellman" santiago,perth,singapore,sydney,brisbane 2 5
sbatch server_script_therm.sh reset reset_7_therm "convex bellman" rome,casablanca,johannesburg,cairo,kawasaki 2 5
sbatch server_script_therm.sh reset reset_8_therm "convex bellman" burlington,oslo,poughkeepsie,paris,osaka 2 5
sbatch server_script_therm.sh reset reset_9_therm "convex bellman" quito,nairobi,kolkata,algiers,kyoto 2 5
